package provider

const SHELL_SCRIPT = "SHELL_SCRIPT"
const DOCKER_IMAGE = "DOCKER_IMAGE"
const KUBERNETES_YAML = "KUBERNETES_YAML"
const HELM_VALUES_YAML = "HELM_VALUES_YAML"
const ECS_TASK_SPEC = "ECS_TASK_SPEC"
